@startuml
actor User

package "View" {
  [OrderBook]
  [OrderTable]
  [OrderRow]
}

database "Model" {
  [WebSocketHandler]
}

component "ViewModel" {
  [OrderBookViewModel]
  [Observer]
}

User --> [OrderBook]
[OrderBook] --> [OrderTable]
[OrderTable] --> [OrderRow]

[OrderTable] --> [OrderBookViewModel] : Use

[OrderBookViewModel] --> [OrderTable] : Manipulate
[OrderBookViewModel] --> [WebSocketHandler] : Use
[OrderBookViewModel] --> [Observer] : Use

[Observer] --> [OrderRow] : Updates

@enduml
