@startuml
actor User

package "View" {
  [OrderBook]
  [OrderTable]
  [OrderRow]
}

database "Model" {
  [WebSocketHandler]
}

component "ViewModel" {
  [OrderBookViewModel]
  [OrderData]
  [Observer]
}

User --> [OrderBook]
[OrderBook] --> [OrderTable]
[OrderTable] --> [OrderRow]
[OrderTable] --> [OrderBookViewModel] : Launches

[OrderBookViewModel] --> [OrderData] : Updates

[WebSocketHandler] --> [OrderBookViewModel] : Updates
[OrderData] --> [Observer] : Updates

[Observer] --> [OrderRow] : Updates

@enduml
